version: '3'

services:
  src:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '80:80'
      - '21:21'
    volumes:
      - laravel_volumes:/var/www/html
    restart: always

volumes:
  laravel_volumes: