version: '3'

services:
  src:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '80:80'
    volumes:
      - ./reappay_superadmin:/var/www/html:cached
    restart: always
    command: apachectl -D FOREGROUND