version: '3'

services:
  src:
    build: .
    ports:
      - '80:80'
      - '22:22'
    volumes:
      - laravel_volumes:/var/www/html
    restart: always
    env_file:
      - .env

volumes:
  laravel_volumes: