version: '3'

services:
  src:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '80:80'
    volumes:
      - ./reappay_superadmin:/var/www/html
    restart: always
    command: php artisan serve --host 0.0.0.0 --port 80